### ISSUE TITLE
NPM documentation incorrect for caching use cases

### ISSUE THREAD

**Issue by epitomus** [sandrinodimattia/axios-token-interceptor#2]
Version: "0.1.0"

Caching section in NPM docs (https://www.npmjs.com/package/axios-token-interceptor#caching), first param to ```tokenCache()``` needs to be a function, e.g. change:

```javascript
const cache = tokenProvider.tokenCache(
  getTokenFromAuthorizationServer().then(res => res.body.access_token),
  { maxAge: ms('8h') }
);
```
to:

```javascript
const cache = tokenProvider.tokenCache(
  () => getTokenFromAuthorizationServer().then(res => res.body.access_token),
  { maxAge: ms('8h') }
);
```

This needs to be fixed for all code blocks in the caching section.

**Comment by lracicot** [comment]
I encountered the same issue. Let's make sure that nobody else loses time on that :) Great library.

**Comment by sandrinodimattia** [comment]
Thanks for the PR, merged!
