### ISSUE TITLE
Unit Mismatch in getToken and Documentation

### ISSUE THREAD

**Issue by cerebralmind** [sandrinodimattia/axios-token-interceptor#5]
It looks like there might be a mismatch between the unit of time used by oauth2 expires_in (seconds) and the expected units used by getToken (milliseconds).

https://github.com/sandrinodimattia/axios-token-interceptor/blob/master/token-cache.js#L32

The documentation seems to imply that this is in seconds

From the documentation:
```const cache = tokenProvider.tokenCache(
  getTokenFromAuthorizationServer().then(res => res.body),
  { getMaxAge: (res) => res.expires_in }
);

cache.reset();```

I ran into this issue while debugging why my tokens were expiring in seconds rather than minutes.

I don't mind opening up a PR with a change in either the README or the tokenCache.

Let me know!

**Comment by miguelrvs** [comment]
Expiration is in milliseconds, while expires_in is in [seconds.]
I proposed PR [https://github.com/sandrinodimattia/axios-token-interceptor/pull/6](url) for this.

**Comment by sandrinodimattia** [comment]
Thanks for reporting this. I updated the guidance in the README to call this out:

```js
const cache = tokenProvider.tokenCache(
  () => getTokenFromAuthorizationServer().then(res => res.body),
  { getMaxAge: (body) => body.expires_in * 1000 }
);
```

I'm not going to change the time unit because it would be a breaking change and it would also impact the `maxAge` setting:

```js
const cache = tokenProvider.tokenCache(
  getTokenFromAuthorizationServer().then(res => res.body.access_token),
  { maxAge: ms('8h') }
);
```
