### ISSUE TITLE
Interceptor does not send post requests

### ISSUE THREAD

**Issue by articga** [sandrinodimattia/axios-token-interceptor#9]
When adding the interceptor all `apiClient.post(...`requests won't get send. Only working with get requests

`apiClient.interceptors.request.use(tokenProvider({
    getToken: () => localStorage.getItem('ttkn').slice(1, -1),
    header: 'access_token',
    headerFormatter: (token) => token
}));`

**Comment by sandrinodimattia** [comment]
Can you provide steps to reproduce? I've added test coverage to show how it works: https://github.com/sandrinodimattia/axios-token-interceptor/commit/841203086fbd605d0aabf479743bcfe4db591b2d#diff-275a6743b2ff7d68e3d76f3462691716R291
